import { Product, Category, Review, Testimonial, Deal, Order, User } from '@/types';

export const allCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest electronics and gadgets',
    image: 'https://placehold.co/400x300/1e293b/ffffff.png?text=Electronics',
    icon: 'Laptop',
    productCount: 156,
    subcategories: [
      { id: 'cat-1-1', name: 'Headphones', slug: 'headphones', description: 'Premium headphones', image: '', icon: 'Headphones', productCount: 45 },
      { id: 'cat-1-2', name: 'Speakers', slug: 'speakers', description: 'Bluetooth speakers', image: '', icon: 'Speaker', productCount: 32 },
      { id: 'cat-1-3', name: 'Smartphones', slug: 'smartphones', description: 'Latest smartphones', image: '', icon: 'Smartphone', productCount: 28 },
    ],
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image: 'https://placehold.co/400x300/c2410c/ffffff.png?text=Fashion',
    icon: 'Shirt',
    productCount: 234,
  },
  {
    id: 'cat-3',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'Everything for your home',
    image: 'https://placehold.co/400x300/16a34a/ffffff.png?text=Home+Living',
    icon: 'Home',
    productCount: 189,
  },
  {
    id: 'cat-4',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Sports gear and outdoor equipment',
    image: 'https://placehold.co/400x300/2563eb/ffffff.png?text=Sports',
    icon: 'Dumbbell',
    productCount: 98,
  },
  {
    id: 'cat-5',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    description: 'Beauty products and health essentials',
    image: 'https://placehold.co/400x300/d97706/ffffff.png?text=Beauty',
    icon: 'Sparkles',
    productCount: 167,
  },
  {
    id: 'cat-6',
    name: 'Books & Stationery',
    slug: 'books-stationery',
    description: 'Books, pens, and office supplies',
    image: 'https://placehold.co/400x300/7c3aed/ffffff.png?text=Books',
    icon: 'BookOpen',
    productCount: 73,
  },
  {
    id: 'cat-7',
    name: 'Toys & Games',
    slug: 'toys-games',
    description: 'Fun toys and board games',
    image: 'https://placehold.co/400x300/ec4899/ffffff.png?text=Toys',
    icon: 'Gamepad2',
    productCount: 112,
  },
  {
    id: 'cat-8',
    name: 'Automotive',
    slug: 'automotive',
    description: 'Car accessories and parts',
    image: 'https://placehold.co/400x300/475569/ffffff.png?text=Automotive',
    icon: 'Car',
    productCount: 54,
  },
];

export const allProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    description: 'Experience premium sound quality with our latest wireless noise-cancelling headphones. Featuring advanced ANC technology, 40-hour battery life, and ultra-comfortable over-ear design. Perfect for music lovers, commuters, and remote workers.',
    shortDescription: 'Premium ANC headphones with 40-hour battery',
    price: 299.99,
    salePrice: 199.99,
    discount: 33,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/1e293b/ffffff.png?text=Headphones+1',
      'https://placehold.co/600x600/334155/ffffff.png?text=Headphones+2',
      'https://placehold.co/600x600/475569/ffffff.png?text=Headphones+3',
      'https://placehold.co/600x600/64748b/ffffff.png?text=Headphones+4',
    ],
    category: 'Electronics',
    categorySlug: 'electronics',
    subcategory: 'Headphones',
    brand: 'SoundMax',
    rating: 4.7,
    reviewCount: 342,
    sku: 'SM-WNC-001',
    inStock: true,
    stockCount: 45,
    colors: [
      { name: 'Midnight Black', value: 'black', hex: '#1e293b' },
      { name: 'Arctic White', value: 'white', hex: '#f8fafc' },
      { name: 'Navy Blue', value: 'navy', hex: '#1e3a5f' },
    ],
    sizes: [],
    tags: ['headphones', 'wireless', 'noise-cancelling', 'bluetooth'],
    isNew: false,
    onSale: true,
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Driver Size': '40mm',
      'Frequency Response': '20Hz - 20kHz',
      'Battery Life': '40 hours',
      'Charging Time': '2 hours',
      'Bluetooth': '5.3',
      'Weight': '250g',
      'Noise Cancellation': 'Active (ANC)',
    },
    createdAt: '2024-12-01',
  },
  {
    id: 'prod-2',
    name: 'Classic Leather Crossbody Bag',
    slug: 'classic-leather-crossbody-bag',
    description: 'Elevate your style with this handcrafted genuine leather crossbody bag. Features multiple compartments, adjustable strap, and premium brass hardware. Ideal for everyday use.',
    shortDescription: 'Handcrafted genuine leather crossbody bag',
    price: 149.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/c2410c/ffffff.png?text=Bag+1',
      'https://placehold.co/600x600/9a3412/ffffff.png?text=Bag+2',
    ],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'UrbanCraft',
    rating: 4.5,
    reviewCount: 128,
    sku: 'UC-CLB-002',
    inStock: true,
    stockCount: 23,
    colors: [
      { name: 'Tan', value: 'tan', hex: '#d2a679' },
      { name: 'Dark Brown', value: 'brown', hex: '#5c3d2e' },
      { name: 'Black', value: 'black', hex: '#1e293b' },
    ],
    sizes: [],
    tags: ['bag', 'leather', 'crossbody', 'fashion'],
    isNew: true,
    onSale: false,
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Material': 'Genuine Leather',
      'Dimensions': '25cm x 18cm x 8cm',
      'Strap Drop': '50-60cm (adjustable)',
      'Closure': 'Magnetic snap',
      'Interior': '2 main compartments, 1 zip pocket',
    },
    createdAt: '2025-01-15',
  },
  {
    id: 'prod-3',
    name: 'Smart Fitness Watch Pro',
    slug: 'smart-fitness-watch-pro',
    description: 'Track your health and fitness with our advanced smartwatch. Features heart rate monitoring, GPS tracking, sleep analysis, and 100+ workout modes. Water-resistant up to 50m.',
    shortDescription: 'Advanced fitness smartwatch with GPS',
    price: 249.99,
    salePrice: 189.99,
    discount: 24,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/2563eb/ffffff.png?text=Watch+1',
      'https://placehold.co/600x600/1d4ed8/ffffff.png?text=Watch+2',
    ],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'FitTech',
    rating: 4.6,
    reviewCount: 567,
    sku: 'FT-SFW-003',
    inStock: true,
    stockCount: 78,
    colors: [
      { name: 'Space Gray', value: 'gray', hex: '#4b5563' },
      { name: 'Rose Gold', value: 'rose', hex: '#f9a8d4' },
      { name: 'Silver', value: 'silver', hex: '#e2e8f0' },
    ],
    sizes: ['S', 'M', 'L'],
    tags: ['watch', 'fitness', 'smart', 'gps'],
    isNew: false,
    onSale: true,
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery Life': '14 days',
      'Water Resistance': '5 ATM (50m)',
      'Sensors': 'Heart rate, SpO2, GPS',
      'Compatibility': 'iOS 14+ / Android 10+',
    },
    createdAt: '2024-11-20',
  },
  {
    id: 'prod-4',
    name: 'Organic Cotton T-Shirt',
    slug: 'organic-cotton-t-shirt',
    description: 'Ultra-soft organic cotton t-shirt made from 100% sustainably sourced cotton. Available in multiple colors and sizes. Perfect for everyday comfort.',
    shortDescription: '100% organic cotton everyday tee',
    price: 34.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/16a34a/ffffff.png?text=Tshirt+1',
      'https://placehold.co/600x600/15803d/ffffff.png?text=Tshirt+2',
    ],
    category: 'Fashion',
    categorySlug: 'fashion',
    brand: 'EcoWear',
    rating: 4.3,
    reviewCount: 89,
    sku: 'EW-OCT-004',
    inStock: true,
    stockCount: 150,
    colors: [
      { name: 'Forest Green', value: 'green', hex: '#16a34a' },
      { name: 'Ocean Blue', value: 'blue', hex: '#3b82f6' },
      { name: 'Sand', value: 'sand', hex: '#d4a373' },
      { name: 'Charcoal', value: 'charcoal', hex: '#374151' },
      { name: 'White', value: 'white', hex: '#ffffff' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    tags: ['t-shirt', 'organic', 'cotton', 'sustainable'],
    isNew: true,
    onSale: false,
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Material': '100% Organic Cotton',
      'Weight': '180 GSM',
      'Fit': 'Regular',
      'Care': 'Machine wash cold',
    },
    createdAt: '2025-02-01',
  },
  {
    id: 'prod-5',
    name: 'Minimalist Desk Lamp',
    slug: 'minimalist-desk-lamp',
    description: 'Modern LED desk lamp with adjustable brightness and color temperature. Features a sleek aluminum body with wireless charging base. Touch controls with memory function.',
    shortDescription: 'LED desk lamp with wireless charging',
    price: 89.99,
    salePrice: 69.99,
    discount: 22,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/f59e0b/ffffff.png?text=Lamp+1',
      'https://placehold.co/600x600/d97706/ffffff.png?text=Lamp+2',
    ],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'LumiCraft',
    rating: 4.8,
    reviewCount: 203,
    sku: 'LC-MDL-005',
    inStock: true,
    stockCount: 34,
    colors: [
      { name: 'Matte Black', value: 'black', hex: '#1e293b' },
      { name: 'Brass', value: 'brass', hex: '#b8860b' },
      { name: 'White', value: 'white', hex: '#f8fafc' },
    ],
    sizes: [],
    tags: ['lamp', 'desk', 'led', 'home'],
    isNew: false,
    onSale: true,
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Light Source': 'LED',
      'Brightness': '800 lumens (adjustable)',
      'Color Temperature': '2700K - 6500K',
      'Material': 'Aluminum + ABS',
      'Wireless Charging': 'Qi certified, 10W',
    },
    createdAt: '2024-10-15',
  },
  {
    id: 'prod-6',
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Professional-grade yoga mat with superior grip and cushioning. Made from eco-friendly TPE material, non-slip on both sides. Includes carrying strap.',
    shortDescription: 'Eco-friendly non-slip yoga mat',
    price: 59.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/7c3aed/ffffff.png?text=Yoga+Mat+1',
      'https://placehold.co/600x600/6d28d9/ffffff.png?text=Yoga+Mat+2',
    ],
    category: 'Sports & Outdoors',
    categorySlug: 'sports-outdoors',
    brand: 'ZenFit',
    rating: 4.4,
    reviewCount: 176,
    sku: 'ZF-YMP-006',
    inStock: true,
    stockCount: 62,
    colors: [
      { name: 'Purple', value: 'purple', hex: '#7c3aed' },
      { name: 'Teal', value: 'teal', hex: '#14b8a6' },
      { name: 'Coral', value: 'coral', hex: '#fb7185' },
    ],
    sizes: [],
    tags: ['yoga', 'mat', 'fitness', 'eco-friendly'],
    isNew: false,
    onSale: false,
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Material': 'TPE (eco-friendly)',
      'Dimensions': '183cm x 61cm x 6mm',
      'Weight': '1.2kg',
      'Surface': 'Double-sided non-slip',
    },
    createdAt: '2024-09-01',
  },
  {
    id: 'prod-7',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: 'Powerful 360-degree sound in a compact waterproof design. 24-hour battery life, built-in microphone, and dual pairing capability.',
    shortDescription: 'Waterproof portable speaker with 24hr battery',
    price: 79.99,
    salePrice: 59.99,
    discount: 25,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/dc2626/ffffff.png?text=Speaker+1',
      'https://placehold.co/600x600/b91c1c/ffffff.png?text=Speaker+2',
    ],
    category: 'Electronics',
    categorySlug: 'electronics',
    subcategory: 'Speakers',
    brand: 'SoundMax',
    rating: 4.5,
    reviewCount: 412,
    sku: 'SM-PBS-007',
    inStock: true,
    stockCount: 89,
    colors: [
      { name: 'Red', value: 'red', hex: '#dc2626' },
      { name: 'Blue', value: 'blue', hex: '#2563eb' },
      { name: 'Black', value: 'black', hex: '#1e293b' },
    ],
    sizes: [],
    tags: ['speaker', 'bluetooth', 'waterproof', 'portable'],
    isNew: false,
    onSale: true,
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Output': '20W',
      'Battery Life': '24 hours',
      'Bluetooth': '5.2',
      'Water Resistance': 'IPX7',
      'Weight': '560g',
    },
    createdAt: '2024-08-15',
  },
  {
    id: 'prod-8',
    name: 'Ceramic Coffee Mug Set',
    slug: 'ceramic-coffee-mug-set',
    description: 'Set of 4 handcrafted ceramic coffee mugs with unique glazed finishes. Each mug holds 350ml and is microwave and dishwasher safe.',
    shortDescription: 'Set of 4 handcrafted ceramic mugs',
    price: 44.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/ea580c/ffffff.png?text=Mugs+1',
      'https://placehold.co/600x600/c2410c/ffffff.png?text=Mugs+2',
    ],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'CraftHome',
    rating: 4.9,
    reviewCount: 94,
    sku: 'CH-CCM-008',
    inStock: true,
    stockCount: 41,
    colors: [
      { name: 'Earth Tones', value: 'earth', hex: '#92400e' },
      { name: 'Ocean Set', value: 'ocean', hex: '#0891b2' },
    ],
    sizes: [],
    tags: ['mug', 'coffee', 'ceramic', 'kitchen'],
    isNew: true,
    onSale: false,
    isFeatured: true,
    isBestSeller: false,
    specifications: {
      'Material': 'Ceramic (lead-free glaze)',
      'Capacity': '350ml each',
      'Set Contents': '4 mugs',
      'Microwave Safe': 'Yes',
      'Dishwasher Safe': 'Yes',
    },
    createdAt: '2025-01-20',
  },
  {
    id: 'prod-9',
    name: 'Running Shoes Ultra Boost',
    slug: 'running-shoes-ultra-boost',
    description: 'High-performance running shoes with responsive cushioning and breathable knit upper. Designed for road running and daily training. Continental rubber outsole for superior grip.',
    shortDescription: 'Performance running shoes with boost cushioning',
    price: 179.99,
    salePrice: 139.99,
    discount: 22,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/0ea5e9/ffffff.png?text=Shoes+1',
      'https://placehold.co/600x600/0284c7/ffffff.png?text=Shoes+2',
    ],
    category: 'Sports & Outdoors',
    categorySlug: 'sports-outdoors',
    brand: 'RunElite',
    rating: 4.6,
    reviewCount: 289,
    sku: 'RE-RUS-009',
    inStock: true,
    stockCount: 56,
    colors: [
      { name: 'Core Black', value: 'black', hex: '#1e293b' },
      { name: 'Cloud White', value: 'white', hex: '#f8fafc' },
      { name: 'Solar Red', value: 'red', hex: '#ef4444' },
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12'],
    tags: ['shoes', 'running', 'sports', 'fitness'],
    isNew: false,
    onSale: true,
    isFeatured: true,
    isBestSeller: true,
    specifications: {
      'Upper': 'Primeknit',
      'Midsole': 'Boost foam',
      'Outsole': 'Continental rubber',
      'Drop': '10mm',
      'Weight': '310g (size 9)',
    },
    createdAt: '2024-11-01',
  },
  {
    id: 'prod-10',
    name: 'Natural Skincare Gift Set',
    slug: 'natural-skincare-gift-set',
    description: 'Luxury skincare gift set features cleanser, toner, serum, and moisturizer. All products are vegan, cruelty-free, and made with organic botanical extracts.',
    shortDescription: 'Vegan 4-piece skincare essentials set',
    price: 89.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/ec4899/ffffff.png?text=Skincare+1',
      'https://placehold.co/600x600/db2777/ffffff.png?text=Skincare+2',
    ],
    category: 'Beauty & Health',
    categorySlug: 'beauty-health',
    brand: 'PureGlow',
    rating: 4.7,
    reviewCount: 156,
    sku: 'PG-NSG-010',
    inStock: true,
    stockCount: 28,
    colors: [],
    sizes: [],
    tags: ['skincare', 'beauty', 'organic', 'gift'],
    isNew: true,
    onSale: false,
    isFeatured: false,
    isBestSeller: false,
    specifications: {
      'Set Contents': 'Cleanser, Toner, Serum, Moisturizer',
      'Skin Type': 'All skin types',
      'Ingredients': 'Organic botanical extracts',
      'Cruelty Free': 'Yes',
      'Vegan': 'Yes',
    },
    createdAt: '2025-02-10',
  },
  {
    id: 'prod-11',
    name: 'Mechanical Gaming Keyboard',
    slug: 'mechanical-gaming-keyboard',
    description: 'RGB mechanical gaming keyboard with hot-swappable switches, N-key rollover, and per-key RGB lighting. Aircraft-grade aluminum frame. Perfect for gamers and typists.',
    shortDescription: 'RGB mechanical keyboard with hot-swap switches',
    price: 129.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/6366f1/ffffff.png?text=Keyboard+1',
      'https://placehold.co/600x600/4f46e5/ffffff.png?text=Keyboard+2',
    ],
    category: 'Electronics',
    categorySlug: 'electronics',
    brand: 'KeyMaster',
    rating: 4.4,
    reviewCount: 198,
    sku: 'KM-MGK-011',
    inStock: true,
    stockCount: 37,
    colors: [
      { name: 'Black', value: 'black', hex: '#1e293b' },
      { name: 'White', value: 'white', hex: '#f8fafc' },
    ],
    sizes: [],
    tags: ['keyboard', 'mechanical', 'gaming', 'rgb'],
    isNew: false,
    onSale: false,
    isFeatured: false,
    isBestSeller: false,
    specifications: {
      'Switch Type': 'Hot-swappable mechanical',
      'Layout': 'Full-size (104 keys)',
      'Backlighting': 'Per-key RGB',
      'Connection': 'USB-C (detachable)',
      'Frame': 'Aircraft-grade aluminum',
    },
    createdAt: '2024-10-01',
  },
  {
    id: 'prod-12',
    name: 'Scented Candle Collection',
    slug: 'scented-candle-collection',
    description: 'Set of 3 hand-poured soy wax scented candles. Fragrances include Lavender Fields, Vanilla Bourbon, and Cedar & Sage. Up to 50 hours burn time each.',
    shortDescription: 'Set of 3 soy wax scented candles',
    price: 38.99,
    currency: 'USD',
    images: [
      'https://placehold.co/600x600/a16207/ffffff.png?text=Candles+1',
      'https://placehold.co/600x600/92400e/ffffff.png?text=Candles+2',
    ],
    category: 'Home & Living',
    categorySlug: 'home-living',
    brand: 'CraftHome',
    rating: 4.8,
    reviewCount: 213,
    sku: 'CH-SCC-012',
    inStock: true,
    stockCount: 55,
    colors: [],
    sizes: [],
    tags: ['candle', 'home', 'scented', 'soy'],
    isNew: false,
    onSale: false,
    isFeatured: false,
    isBestSeller: true,
    specifications: {
      'Wax': '100% Natural Soy',
      'Burn Time': 'Up to 50 hours each',
      'Fragrances': 'Lavender, Vanilla, Cedar',
      'Wick': 'Cotton (lead-free)',
      'Set Contents': '3 candles (200g each)',
    },
    createdAt: '2024-09-15',
  },
];

export const allReviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    author: 'Sarah M.',
    avatar: 'https://placehold.co/40x40/c2410c/ffffff.png?text=SM',
    rating: 5,
    title: 'Best headphones I\'ve ever owned!',
    comment: 'The noise cancellation is incredible. I use these for work calls and music, and the sound quality is phenomenal. Battery life easily lasts a week with heavy use.',
    date: '2025-01-15',
    helpful: 24,
    verified: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    author: 'James K.',
    avatar: 'https://placehold.co/40x40/2563eb/ffffff.png?text=JK',
    rating: 4,
    title: 'Great sound, slightly tight fit',
    comment: 'Sound quality and ANC are top-notch. My only complaint is the ear cups could be a bit larger for big ears. Otherwise, excellent value for the price.',
    date: '2025-01-10',
    helpful: 12,
    verified: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-1',
    author: 'Emily R.',
    avatar: 'https://placehold.co/40x40/16a34a/ffffff.png?text=ER',
    rating: 5,
    title: 'Worth every penny',
    comment: 'Upgraded from a cheaper pair and the difference is night and day. The ANC blocks out everything — subway noise, office chatter, you name it.',
    date: '2024-12-28',
    helpful: 18,
    verified: true,
  },
  {
    id: 'rev-4',
    productId: 'prod-3',
    author: 'Mike T.',
    avatar: 'https://placehold.co/40x40/d97706/ffffff.png?text=MT',
    rating: 5,
    title: 'Perfect fitness companion',
    comment: 'This watch tracks everything I need — heart rate, GPS for runs, sleep tracking. The battery lasts almost two weeks. Highly recommend for anyone serious about fitness.',
    date: '2025-02-01',
    helpful: 31,
    verified: true,
  },
  {
    id: 'rev-5',
    productId: 'prod-5',
    author: 'Lisa W.',
    avatar: 'https://placehold.co/40x40/7c3aed/ffffff.png?text=LW',
    rating: 5,
    title: 'Beautiful and functional',
    comment: 'This lamp is stunning on my desk. The wireless charging is a great bonus — I just place my phone on the base. The adjustable brightness is smooth and the warm light is very comfortable.',
    date: '2024-11-20',
    helpful: 15,
    verified: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    author: 'Jennifer L.',
    avatar: 'https://placehold.co/48x48/c2410c/ffffff.png?text=JL',
    rating: 5,
    quote: 'Cartziio has become my go-to marketplace. The product quality is always excellent and shipping is incredibly fast. Highly recommend!',
    location: 'New York, USA',
  },
  {
    id: 'test-2',
    author: 'David C.',
    avatar: 'https://placehold.co/48x48/2563eb/ffffff.png?text=DC',
    rating: 5,
    quote: 'I love the variety of products available on Cartziio. Found some unique items that I couldn\'t find anywhere else. Customer support is also top-notch.',
    location: 'Toronto, Canada',
  },
  {
    id: 'test-3',
    author: 'Marie D.',
    avatar: 'https://placehold.co/48x48/16a34a/ffffff.png?text=MD',
    rating: 4,
    quote: 'Great shopping experience overall. The return process was smooth when I needed to exchange a size. Will definitely shop here again.',
    location: 'Montreal, Canada',
  },
];

export const allDeals: Deal[] = [
  {
    id: 'deal-1',
    product: allProducts[0],
    originalPrice: 299.99,
    dealPrice: 199.99,
    discountPercent: 33,
    endsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'flash',
  },
  {
    id: 'deal-2',
    product: allProducts[2],
    originalPrice: 249.99,
    dealPrice: 189.99,
    discountPercent: 24,
    endsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'daily',
  },
  {
    id: 'deal-3',
    product: allProducts[4],
    originalPrice: 89.99,
    dealPrice: 69.99,
    discountPercent: 22,
    endsAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'flash',
  },
  {
    id: 'deal-4',
    product: allProducts[6],
    originalPrice: 79.99,
    dealPrice: 59.99,
    discountPercent: 25,
    endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'limited',
  },
  {
    id: 'deal-5',
    product: allProducts[8],
    originalPrice: 179.99,
    dealPrice: 139.99,
    discountPercent: 22,
    endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'daily',
  },
];

export const mockUser: User = {
  id: 'user-1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  avatar: 'https://placehold.co/80x80/c2410c/ffffff.png?text=JD',
  joinDate: '2024-06-15',
  addresses: [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '+1 555-0123',
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'US',
      isDefault: true,
    },
  ],
};

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'CZ-ABC123-XY01',
    items: [
      { product: allProducts[0], quantity: 1, selectedColor: 'black' },
      { product: allProducts[7], quantity: 2 },
    ],
    subtotal: 289.97,
    shipping: 0,
    tax: 23.20,
    discount: 0,
    total: 313.17,
    status: 'delivered',
    shippingAddress: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      phone: '+1 555-0123',
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'US',
    },
    paymentMethod: 'Credit Card',
    createdAt: '2025-01-05',
    estimatedDelivery: '2025-01-10',
  },
  {
    id: 'order-2',
    orderNumber: 'CZ-DEF456-AB02',
    items: [
      { product: allProducts[3], quantity: 3, selectedColor: 'green', selectedSize: 'L' },
    ],
    subtotal: 104.97,
    shipping: 5.99,
    tax: 8.40,
    discount: 0,
    total: 119.36,
    status: 'shipped',
    shippingAddress: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      phone: '+1 555-0123',
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'US',
    },
    paymentMethod: 'PayPal',
    createdAt: '2025-02-15',
    estimatedDelivery: '2025-02-22',
  },
];

export const popularSearches = [
  'wireless headphones',
  'running shoes',
  'desk lamp',
  'leather bag',
  'yoga mat',
  'skincare set',
];

export const brandLogos = [
  { name: 'SoundMax', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=SoundMax' },
  { name: 'UrbanCraft', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=UrbanCraft' },
  { name: 'FitTech', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=FitTech' },
  { name: 'EcoWear', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=EcoWear' },
  { name: 'LumiCraft', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=LumiCraft' },
  { name: 'ZenFit', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=ZenFit' },
  { name: 'CraftHome', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=CraftHome' },
  { name: 'PureGlow', logo: 'https://placehold.co/120x40/1e293b/ffffff.png?text=PureGlow' },
];

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return allProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return allCategories.find((c) => c.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return allProducts.filter((p) => p.isFeatured);
}

export function getBestSellers(): Product[] {
  return allProducts.filter((p) => p.isBestSeller);
}

export function getNewArrivals(): Product[] {
  return allProducts.filter((p) => p.isNew);
}

export function getOnSaleProducts(): Product[] {
  return allProducts.filter((p) => p.onSale);
}

export function getProductReviews(productId: string): Review[] {
  return allReviews.filter((r) => r.productId === productId);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return allProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}
